### ISSUE TITLE
请求添加高亮原创内容的功能。

### ISSUE THREAD

**Issue by angryLid** [superPufferfish/custom-zhihu#1]
我只想看关注的人的原创部分（回答了问题，发表了文章），不想看转推的内容（点赞了回答，收藏了回答），有没有办法优化一下。

**Comment by superPufferfish** [comment]
> 我只想看关注的人的原创部分（回答了问题，发表了文章），不想看转推的内容（点赞了回答，收藏了回答），有没有办法优化一下。

功能添加了，添加关注人原创内容高亮和关注人动态过滤的功能。
