### ISSUE TITLE
没法屏蔽掉视频

### ISSUE THREAD

**Issue by xibaibai9527** [superPufferfish/custom-zhihu#11]
推荐栏的视频依旧存在，已经勾选上屏蔽视频功能也不行

**Comment by superPufferfish** [comment]
![image](https://user-images.githubusercontent.com/33803840/140244277-bdfa81d7-40e2-46f4-a8b1-b88d54a34535.png)
是这个模块吗，屏蔽视频只是屏蔽推荐列表的视频内容，比如下面这个

**Comment by liangliangle** [comment]
目前无法屏蔽推荐列表的视频，比如你这个截图中的第一个【以太坊**】，目前的在AdBlock屏蔽给规则
 zhihu.com##[data-za-extra-module*="\"has_video\":true"]

参考以下文章的评论区：https://zhuanlan.zhihu.com/p/149985612

**Comment by superPufferfish** [comment]
对啊，我这可以屏蔽的，你那配置是什么

**Comment by liangliangle** [comment]
> 对啊，我这可以屏蔽的，你那配置是什么

已经找到选项了，【列表视频回答的内容】
