### ISSUE TITLE
视频回答、购物链接屏蔽失效

### ISSUE THREAD

**Issue by superfreeman1989** [superPufferfish/custom-zhihu#14]
rt，目前貌似这两种链接模块不管是文章还是回答内都照常显示

**Comment by superfreeman1989** [comment]
补充，另外知乎官方盐选类账号回答屏蔽也似乎失效了

**Comment by superPufferfish** [comment]
有木有对应的页面可以查看的

**Comment by superfreeman1989** [comment]
购物链接：https://www.zhihu.com/question/489133060/answer/2175135680
视频回答：https://www.zhihu.com/question/286525154

**Comment by superPufferfish** [comment]
v2.7.3 已经修复，感谢

**Comment by superfreeman1989** [comment]
确认。多谢大佬
