### ISSUE TITLE
1000px会让知乎文章过宽

### ISSUE THREAD

**Issue by Yoho777** [superPufferfish/custom-zhihu#16]
version:2.6.25

首先，这个插件太好用辣(≧▽≦)

版心1000px以下更窄的同时，的确，会让搜索页这种带「边栏」的页面出现严重的挤压，但是「文章/专栏」是没有「边栏」的，直接拉满非常难看QuQ
我现在自己改代码降到了800px，并隐藏掉了所有的边栏来避免挤压，也许将「文章/专栏」单独拉出来处理比较好？

顺带一提，「隐藏模块-收藏喜欢举报」在详情界面会因为「举报」收到了「···」里面没有没有被屏蔽掉；「隐藏模块-回答按钮」好像没有起到作用，但是「隐藏模块-关注问题按钮」「隐藏模块-邀请回答按钮」就可以…

另外，知乎用户的「个人页面」我觉得可以加入隐藏模块，像什么「个人成就」啦，「关注的话题/专栏/问题」等等。话说隐藏模块有一些的说明有点抽象，很多我都是来回试了几遍才理解的=_=

最后，个人觉得「直达问题按钮」（去除url中answer以后的部分）和「快捷收起当前回答/评论」（点击两侧空白处）是[类似插件](https://greasyfork.org/zh-CN/scripts/419081-%E7%9F%A5%E4%B9%8E%E5%A2%9E%E5%BC%BA)的两个不错的小功能，可以加加～

**Comment by superPufferfish** [comment]
2.6.26 专栏文章版心宽度抽离
