### ISSUE TITLE
你好!想要收藏这个按钮,但是极简模式下太多设置不知道怎么找

### ISSUE THREAD

**Issue by LeokuJessica** [superPufferfish/custom-zhihu#17]

**Comment by superPufferfish** [comment]
收藏什么按钮？可以描述具体一些吗😳

**Comment by LeokuJessica** [comment]
就是比如说这回答不错，想要收藏，但是回答低栏只有赞同和添加评论两个按钮（不知道是我设置问题还是有插件冲突）😂





------------------ 原始邮件 ------------------
发件人: liuyubing ***@***.***&gt;
发送时间: 2022年1月30日 20:13
收件人: superPufferfish/custom-zhihu ***@***.***&gt;
抄送: Shiga ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [superPufferfish/custom-zhihu] 你好!想要收藏这个按钮,但是极简模式下太多设置不知道怎么找 (Issue #17)





 
收藏什么按钮？可以描述具体一些吗😳
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by superPufferfish** [comment]
![image](https://user-images.githubusercontent.com/33803840/151990921-61ae577f-ad0e-4c86-a250-16ad2feeaf3b.png)
极简模式下默认隐藏了这个按钮，我的问题，后续修改一下在极简模式下不隐藏这几个按钮。。

**Comment by LeokuJessica** [comment]
谢谢！新年快乐！！





------------------ 原始邮件 ------------------
发件人: liuyubing ***@***.***&gt;
发送时间: 2022年2月1日 22:50
收件人: superPufferfish/custom-zhihu ***@***.***&gt;
抄送: Shiga ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [superPufferfish/custom-zhihu] 你好!想要收藏这个按钮,但是极简模式下太多设置不知道怎么找 (Issue #17)





 

 极简模式下默认隐藏了这个按钮，我的问题，后续修改一下在极简模式下不隐藏这几个按钮。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
