### ISSUE TITLE
希望作者能添加一个批量导出收藏夹答案的功能，导出格式为pdf，epub都行，谢谢作者提供这么好用的插件。

### ISSUE THREAD

**Issue by whoarethey** [superPufferfish/custom-zhihu#2]

**Comment by superPufferfish** [comment]
请问批量导出收藏夹答案是什么意思，把问题和收藏的回答导出吗？

**Comment by superPufferfish** [comment]
功能添加啦 https://github.com/superPufferfish/custom-zhihu#5-%E6%94%B6%E8%97%8F%E5%A4%B9%E5%86%85%E5%AE%B9%E5%AF%BC%E5%87%BA%E4%B8%BApdf
