### ISSUE TITLE
希望增加清理“关注的问题”相关功能

### ISSUE THREAD

**Issue by RxinnotRstar** [superPufferfish/custom-zhihu#38]
比如说，可以在 我的-关注-我关注的问题 里增加一个“删除全部”按钮（蓝色方框处），或者在每条关注的问题处增加“取消关注”按钮（绿色方框处）
![图片](https://user-images.githubusercontent.com/56676566/197070781-143c3b6b-2221-4602-81d0-c7b965bb9b54.png)

**Comment by superPufferfish** [comment]
经过调试，知乎服务端添加了接口页面 「x-zst-81」和 「x-zse-96」header 的判断，无法跨页面获取及访问，所以这个功能木有办法实现。

**Comment by RxinnotRstar** [comment]
> 经过调试，知乎服务端添加了接口页面 「x-zst-81」和 「x-zse-96」header 的判断，无法跨页面获取及访问，所以这个功能木有办法实现。

有没有什么办法可以在用户的电脑上自动打开新标签页，再自动点击取关，最后自动关闭标签页？

**Comment by superPufferfish** [comment]
> > 经过调试，知乎服务端添加了接口页面 「x-zst-81」和 「x-zse-96」header 的判断，无法跨页面获取及访问，所以这个功能木有办法实现。
> 
> 有没有什么办法可以在用户的电脑上自动打开新标签页，再自动点击取关，最后自动关闭标签页？

更新到最新版本，可以了，但是为了性能只放了单个取关的按钮
