### ISSUE TITLE
隐藏详情右侧信息栏后感觉有点宽

### ISSUE THREAD

**Issue by enterlet** [superPufferfish/custom-zhihu#4]
隐藏详情右侧信息栏后感觉有点宽，能否加个设置，就是像首页信息流一样，能窄一点
还有专栏文章也感觉有点宽

**Comment by superPufferfish** [comment]
页面宽度是按照版心大小来的，列表看起来窄是因为两侧有其它模块，如果小于1000像素的话，就会出现积压问题，详情看起来宽是因为最小就是1000了，后面要窄一点的我后续再看看有没有更好的优化方式。

**Comment by superPufferfish** [comment]
专栏文章宽度设置抽离
