### ISSUE TITLE
你好朋友 请问直接屏蔽问题是否可行？

### ISSUE THREAD

**Issue by SKT-Badwoman** [superPufferfish/custom-zhihu#42]
你好朋友，谢谢你制作这个插件，如果有赞赏途径的话请告诉我。另外请问是否可以直接屏蔽某个问题？如果可以的话，可不可以制作一个在浏览时屏蔽刷到的某一问题或者屏蔽某条回答的边栏浮动式快捷按钮？这样需要屏蔽的时候可以直接点击来屏蔽用户或者屏蔽某条回答或者屏蔽此问题。如果描述的不够确切 请告诉我 我会给出更详细的描述

**Comment by superPufferfish** [comment]
> 你好朋友，谢谢你制作这个插件，如果有赞赏途径的话请告诉我。另外请问是否可以直接屏蔽某个问题？如果可以的话，可不可以制作一个在浏览时屏蔽刷到的某一问题或者屏蔽某条回答的边栏浮动式快捷按钮？这样需要屏蔽的时候可以直接点击来屏蔽用户或者屏蔽某条回答或者屏蔽此问题。如果描述的不够确切 请告诉我 我会给出更详细的描述

可以在「过滤内容」-「列表屏蔽关键词」设置问题关键词屏蔽，屏蔽用户回答可以在「已屏蔽」用户列表查看
