### ISSUE TITLE
貌似知乎有反制措施

### ISSUE THREAD

**Issue by cuiweiqiang** [superPufferfish/custom-zhihu#8]
目前不确定现象是否典型，在页面向下滚动多次必出现知乎错误页，关闭配置后没有该现象。
浏览器：93.0.4577.63 (Official Build) (arm64)
系统：macOS 11.5.2
示例页面：https://www.zhihu.com/question/386877187
（不限于这一个，普遍现象，举例这一个）
配置：`{"chooseHeart":"system","versionHeart":"1200","versionHeartSelf":"1200","positionAnswer":"left","positionAnswerIndex":"1","positionCreation":"right","positionCreationIndex":"2","positionTable":"right","positionTableIndex":"3","positionFavorites":"left","positionFavoritesIndex":"4","positionFooter":"right","positionFooterIndex":"5","stickyLeft":false,"stickyRight":false,"zoomAnswerImage":"default","titleIco":"","title":"","colorBackground":"#ffffff","customizeCss":"","questionTitleTag":true,"fixedListItemMore":false,"shoppingLink":"default","answerVideoLink":"default","filterKeywords":[],"showGIFinDialog":true,"zoomAnswerText":false,"isUseThemeDark":false,"notificationAboutFilter":false,"questionCreatedAndModifiedTime":true,"answerUnfold":false,"answerFoldStart":true,"highlightOriginal":true,"listOutPutNotInterested":false,"highlightListItem":false,"articleCreateTimeToTop":true,"listItemCreatedAndModifiedTime":true,"answerItemCreatedAndModifiedTime":true,"indexPathnameRedirect":"n","showBlockUser":true,"suspensionHomeTab":false,"suspensionHomeTabPo":"left: 20px; top: 100px;","suspensionHomeTabFixed":true,"suspensionHomeTabStyle":"transparent","suspensionFind":false,"suspensionFindPo":"left: 10px; top: 380px;","suspensionFindFixed":true,"suspensionFindStyle":"transparent","suspensionSearch":false,"suspensionSearchPo":"left: 200px; top: 100px;","suspensionSearchFixed":true,"suspensionUser":false,"suspensionUserPo":"right: 60px; top: 100px;","suspensionUserFixed":true,"suspensionPickUp":true,"previewOpenGIF":true,"toHomeButton":true,"toHomeButtonZhuanlan":"zhihu","hiddenAnswerRightFooter":true,"hiddenFixedActions":false,"hiddenLogo":false,"hiddenHeader":false,"hiddenHeaderScroll":false,"hiddenItemActions":false,"hiddenAnswerText":false,"hiddenQuestionShare":false,"hiddenQuestionTag":false,"hiddenQuestionActions":false,"hiddenReward":false,"hiddenZhuanlanTag":false,"hiddenListImg":false,"hiddenReadMoreText":true,"hiddenAD":true,"hiddenAnswerRights":false,"hiddenAnswerRightsText":false,"hiddenAnswers":false,"hiddenHotListWrapper":false,"hiddenZhuanlanActions":false,"hiddenZhuanlanTitleImage":false,"hiddenHotItemMetrics":false,"hiddenHotItemIndex":false,"hiddenHotItemLabel":false,"hiddenDetailAvatar":false,"hiddenDetailBadge":false,"hiddenDetailVoters":false,"hiddenDetailName":false,"hiddenHomeTab":false,"hiddenQuestionSide":false,"hiddenQuestionFollowing":false,"hiddenQuestionAnswer":false,"hiddenQuestionInvite":false,"hiddenSearchBoxTopSearch":false,"hiddenSearchPageTopSearch":false,"hiddenSearchPageFooter":false,"hiddenSearchPageListAD":false,"hiddenZhuanlanShare":false,"hiddenZhuanlanVoters":false,"hiddenCollegeEntranceExamination":true,"hiddenListAnswerInPerson":false,"hiddenFollowAction":false,"hiddenFollowChooseUser":false,"hiddenAnswerRightFooterAnswerAuthor":false,"hiddenAnswerRightFooterFavorites":false,"hiddenAnswerRightFooterRelatedQuestions":false,"hiddenAnswerRightFooterContentList":false,"hiddenAnswerRightFooterFooter":false,"hidden618HongBao":true,"hiddenZhuanlanFollowButton":false,"hiddenZhuanlanAvatarWrapper":false,"hiddenZhuanlanAuthorInfoHead":false,"hiddenZhuanlanAuthorInfoDetail":false,"hiddenQuestionTopic":false,"hiddenQuestionSpecial":false,"removeStoryAnswer":true,"removeYanxuanAnswer":true,"removeYanxuanRecommend":true,"removeFromYanxuan":true,"removeZhihuOfficial":false,"removeItemAboutArticle":false,"removeItemAboutAnswer":false,"removeItemAboutVideo":false,"removeItemAboutAsk":true,"removeFollowVoteAnswer":false,"removeFollowVoteArticle":false,"removeFollowFQuestion":false,"removeBlockUserContent":true,"removeBlockUserContentList":[{"id":"ee163186b50b8d289104d8aa86050862","name":"陈彬","avatar":"https://pic2.zhimg.com/50/e42727a7070d6b468845c0f5b16b9fb2_l.jpg","userType":"people","urlToken":"chen-bin-74-88-32"},{"id":"7b54fb8d04f23ca58d3a25585301f5df","name":"蓝大仙人","avatar":"https://pic2.zhimg.com/50/v2-79d95f1ab0bfc3b4992b2bc1f71af22b_l.jpg","userType":"people","urlToken":"lan-da-xian-ren"},{"id":"9692c15dd4953b26bf83257c0c713293","name":"臭氧不是毒","avatar":"https://pic3.zhimg.com/50/v2-7c3aed8351515bd834c4f93c07c4cb9c_l.jpg","userType":"people","urlToken":"chou-yang-bu-shi-du"},{"id":"d5f21c511a68afa715e1b5cfe8533794","name":"老丈人说车","avatar":"https://pic1.zhimg.com/50/v2-6cbe9b0878ec891d60d8536b29e0f969_l.jpg","userType":"people","urlToken":"lao-zhang-ren-shuo-che"},{"id":"e7bd77b7a35455562b5f52c7fb8905e3","name":"李大锤同学","avatar":"https://pic3.zhimg.com/50/v2-3161a7b580578c4b2c018e5eda0bb49f_l.jpg","userType":"people","urlToken":"li-ze-xi-27"},{"id":"f5a6888c26a9c7f05d87ffe45b2d0bed","name":"老爸评测","avatar":"https://pic3.zhimg.com/50/v2-86e8a18c0d41ab07acd82410c42f065a_l.jpg","userType":"organization","urlToken":"lao-ba-ping-ce"},{"id":"d8b892ba937a43f8c0a6697503e06ba1","name":"祝晓晗","avatar":"https://pic2.zhimg.com/50/v2-85db9e541fda3ae925cb7a3d3111ec39_l.jpg","userType":"people","urlToken":"zhu-xiao-han-15-23"},{"id":"077e9cbb72958d6ba13725375cfe54e2","name":"Isakkkk030","avatar":"https://pic2.zhimg.com/50/v2-ebfe27e8f79c721cf19ea79bc825aad8_l.jpg","userType":"people","urlToken":"yixie-zhi-qiu-69-9-8"},{"id":"8f426ddd5236084fa579ba63323aaa7c","name":"圆圆","avatar":"https://pic1.zhimg.com/50/v2-dc16dfbbeb3662c20d5369b1bb454833_l.jpg","userType":"people","urlToken":"zhao-kun-chi-71"},{"id":"7be8d9306685fa07fc71375e1c20856c","name":"帅哥","avatar":"https://pic2.zhimg.com/50/v2-07a9fc91cc186417c179ffea0b95d0f4_l.jpg","userType":"people","urlToken":"ke-ai-mou"},{"id":"a6813fe8112c7ac542110da49bd3b3d5","name":"酒酿樱桃","avatar":"https://pic3.zhimg.com/50/v2-cb7e6fdcc00ded76ac2eac2533d0e9dd_l.jpg","userType":"people","urlToken":"zhoucc008"},{"id":"5b61bdd870b99af12c4d82972106fb92","name":"大咸凉湿","avatar":"https://pic4.zhimg.com/50/v2-acdb3a8e68fa41c2593c66fac334f4d1_l.jpg","userType":"people","urlToken":"dao-wai-zhen-ren"},{"id":"4b9f3dc9ccc6e64c85857e913ed8db27","name":"女王viisee吴","avatar":"https://pic1.zhimg.com/50/v2-9be4bec138618efadac37a2939236d1f_l.jpg","userType":"people","urlToken":"viiseewu"},{"id":"0970f947b898ecc0ec035f9126dd4e08","name":"梅启铭","avatar":"https://pic1.zhimg.com/50/da8e974dc_l.jpg","userType":"people","urlToken":"excited-vczh"},{"id":"5552cbf7c6e4f756b07fdcf495222b44","name":"EnTaroAdun","avatar":"https://pic4.zhimg.com/50/v2-90d38e5dee377710a2d2bd5a2663442c_l.jpg","userType":"people","urlToken":"wang-hai-58-13"},{"id":"2fd04cdccf4012a2c294a62eb60409e3","name":"肖进","avatar":"https://pic4.zhimg.com/50/da8e974dc_l.jpg","userType":"people","urlToken":"showjim"},{"id":"7532d3f09a88c32da254f34e3e23b916","name":"唧唧","avatar":"https://pic2.zhimg.com/50/a1f99112c6f55c3c6ccae6148ffee6c9_l.jpg","userType":"people","urlToken":"gai-yin-18"},{"id":"172bdd3dc7eb563194150c423a6014d4","name":"沪生","avatar":"https://pic2.zhimg.com/50/v2-5b36e35e67e0d8689be25f3bf230b4de_l.jpg","userType":"people","urlToken":"fadsfkgfew"},{"id":"fd4f53b430b1d677e18053e45507b9e8","name":"叶泊枫","avatar":"https://pic1.zhimg.com/v2-428f033ee9bf5a58e0d381236a76321e_l.jpg?source=1940ef5c","userType":"people","urlToken":"Yefeng7"},{"id":"","name":"赵爵爷","avatar":"https://pic1.zhimg.com/50/v2-975f5cc6b376b4539d3767761bd98009_m.jpg","userType":"people","urlToken":"fei-cheng-68-6"},{"id":"","name":"汪汪大海","avatar":"https://pic1.zhimg.com/50/v2-3391f8c1bb546d722ebbdcaa5ffd14f2_m.jpg","userType":"people","urlToken":"wang-wang-da-hai-5"}],"t":1631501952377}`

**Comment by superPufferfish** [comment]
我的问题，已经修复了
